### ISSUE TITLE
Event list screen

### ISSUE THREAD

**Issue by sr-meh** [BrightCoders-Institute/reto-administrador-de-eventos-jdg#3]
- When selecting the "Start" option in the menu, the application should redirect the user to a new screen.
- 
- On this screen, all recorded events should be displayed.
- 
- For each event, the following details must be displayed:

  - Title: The title of the event.
  - Description: The description of the event.
  - Date: The date of the event.
  - Location: The location of the event.
  - Cost: The cost of the event.

**Comment by Ballo1988** [comment]
This issue was move to Navigation Menu, see this change here #2
